---
title: "p"
author: "Arthur Johnson"
date: "2024-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

dir_meeting_minutes <- "/Users/arthurjohnson/Downloads/fomc-hawkish-dovish/data/filtered_data/meeting_minutes_labeled"
dir_press_conference <- "/Users/arthurjohnson/Downloads/fomc-hawkish-dovish/data/filtered_data/press_conference_labeled"
dir_speeches <- "/Users/arthurjohnson/Downloads/fomc-hawkish-dovish/data/filtered_data/speech_labeled"

pattern_meeting_minutes <- "labeled_\\d{8}_filtered\\.csv"
pattern_press_conference <- "labeled_FOMCpresconf\\d{8}_select_filtered\\.csv"
pattern_speeches <- "labeled_.*_filtered\\.csv"  

files_meeting_minutes <- list.files(
  path = dir_meeting_minutes, 
  pattern = pattern_meeting_minutes, 
  full.names = TRUE
)

files_press_conference <- list.files(
  path = dir_press_conference, 
  pattern = pattern_press_conference, 
  full.names = TRUE
)

files_speeches <- list.files(
  path = dir_speeches, 
  pattern = pattern_speeches, 
  full.names = TRUE
)

file_list <- data.frame(
  file_path = c(files_meeting_minutes, files_press_conference, files_speeches),
  type = c(
    rep("meeting_minutes", length(files_meeting_minutes)),
    rep("press_conference", length(files_press_conference)),
    rep("speech", length(files_speeches))
  ),
  stringsAsFactors = FALSE
)

df_list <- list()

for (i in seq_len(nrow(file_list))) {
  file <- file_list$file_path[i]
  type <- file_list$type[i]
  
  df <- read_csv(file)
  
  filename <- basename(file)
  
  date_match <- NA
  speaker <- NA
  
  if (type == "meeting_minutes") {
    date_match <- str_extract(filename, "\\d{8}")
    date_format <- "%Y%m%d"
  } else if (type == "press_conference") {
    date_match <- str_extract(filename, "(?<=FOMCpresconf)\\d{8}")
    date_format <- "%Y%m%d"
  } else if (type == "speech") {
    
    match <- str_match(filename, "labeled_(.+?)(\\d{8}[a-z]?)(_filtered\\.csv)")
    
    if (!is.na(match[1, 1])) {
      speaker <- match[1, 2]
      date_match <- str_extract(match[1, 3], "\\d{8}")
      date_format <- "%Y%m%d"
    } else {
      date_match <- str_extract(filename, "\\d{8}")
      date_format <- "%Y%m%d"
    }
  }
  
  date_parsed <- as.Date(date_match, format = date_format)
  
  df <- df %>%
    mutate(
      date = date_parsed,
      type = type,
      speaker = speaker
    )
  
  df_list[[length(df_list) + 1]] <- df
}

combined_df <- bind_rows(df_list)

combined_csv_path <- "/Users/arthurjohnson/Downloads/combined_speeches.csv"
write_csv(combined_df, combined_csv_path)

cat("Combined CSV file saved as", combined_csv_path, "\n")

```

```{r}
combined_speeches<-read.csv("/Users/arthurjohnson/Downloads/combined_speeches.csv")
```

```{r}
combined_speeches<-combined_speeches %>% select(-speaker)
```

```{r}
combined_speeches <- combined_speeches %>% arrange(date)
```

GETTING FINANCIAL DATA

S&P500
```{r}

sp500_data <- tq_get("^GSPC", get = "stock.prices", from = "1990-01-01")

sp500_returns <- sp500_data %>%
  tq_transmute(select = adjusted,           
               mutate_fun = periodReturn,  
               period = "daily",         
               type = "log",            
               col_rename = "sp500_return") 

sp500_returns$date <- as.Date(sp500_returns$date)

```
VIX
```{r}
vix_data <- tq_get("^VIX", get = "stock.prices", from = "1990-01-01")
vix_data$date <- as.Date(vix_data$date)
vix_data <- vix_data %>% select(date, VIX_close = adjusted)
```
SPY Volume
```{r}
spy_data <- tq_get("SPY", get = "stock.prices", from = "1990-01-01")
spy_data$date <- as.Date(spy_data$date)

spy_volume <- spy_data %>% select(date, volume)

```
Treasury Yields
```{r}
getSymbols("DGS2", src = "FRED")
dgs2_data <- data.frame(date = index(DGS2), DGS2 = as.numeric(DGS2))

getSymbols("DGS10", src = "FRED")
dgs10_data <- data.frame(date = index(DGS10), DGS10 = as.numeric(DGS10))

dgs2_data$date <- as.Date(dgs2_data$date)
dgs10_data$date <- as.Date(dgs10_data$date)
yield_curve <- merge(dgs2_data, dgs10_data, by = "date", all = TRUE) %>%
  mutate(yield_curve_slope = DGS10 - DGS2)

```
FFR
```{r}
getSymbols("FEDFUNDS", src = "FRED")
fedfunds_data <- data.frame(date = index(FEDFUNDS), fed_funds_rate = as.numeric(FEDFUNDS))
fedfunds_data$date <- as.Date(fedfunds_data$date)

```
CPI
```{r}
getSymbols("CPIAUCSL", src = "FRED")
cpi_data <- data.frame(date = index(CPIAUCSL), CPI = as.numeric(CPIAUCSL))
cpi_data$date <- as.Date(cpi_data$date)

cpi_data <- cpi_data %>%
  arrange(date) %>%
  mutate(inflation_rate = (CPI / lag(CPI, 12) - 1) * 100)

```
PPI
```{r}
getSymbols("PPIACO", src = "FRED")
ppi_data <- data.frame(date = index(PPIACO), PPI = as.numeric(PPIACO))
ppi_data$date <- as.Date(ppi_data$date)

ppi_data <- ppi_data %>%
  arrange(date) %>%
  mutate(ppi_inflation_rate = (PPI / lag(PPI, 12) - 1) * 100)

```
Total FED Assets
```{r}
getSymbols("WALCL", src = "FRED")
balance_sheet_data <- data.frame(date = index(WALCL), total_assets = as.numeric(WALCL))
balance_sheet_data$date <- as.Date(balance_sheet_data$date)

```

MERGING DATA


```{r}

library(timeDate)
years <- 1990:2025  
holidaysNYSE <- timeDate::holidayNYSE(year = years)
cal <- create.calendar(name = "NYSE", holidays = holidaysNYSE, weekdays = c("saturday", "sunday"))
combined_speeches1 <- combined_speeches1 %>%
  mutate(trading_date = adjust.next(date, cal))
```

```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(sp500_returns, by = c("trading_date" = "date"))
```
```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(vix_data, by = c("trading_date" = "date"))

```
```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(spy_volume, by = c("trading_date" = "date"))

```
```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(yield_curve %>% select(date, DGS2, DGS10, yield_curve_slope), by = c("trading_date" = "date"))

```
```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(fedfunds_data, by = c("trading_date" = "date"))

```


```{r}
cpi_data_filled <- cpi_data %>%
  arrange(date) %>%
  tidyr::fill(inflation_rate, .direction = "down")
combined_speeches1 <- combined_speeches1 %>%
  left_join(cpi_data_filled %>% select(date, inflation_rate), by = c("trading_date" = "date"))
```
```{r}
ppi_data_filled <- ppi_data %>%
  arrange(date) %>%
  tidyr::fill(ppi_inflation_rate, .direction = "down")

combined_speeches1 <- combined_speeches1 %>%
  left_join(ppi_data_filled %>% select(date, ppi_inflation_rate), by = c("trading_date" = "date"))

```
```{r}
balance_sheet_data_filled <- balance_sheet_data %>%
  arrange(date) %>%
  tidyr::fill(total_assets, .direction = "down")

combined_speeches1 <- combined_speeches1 %>%
  left_join(balance_sheet_data_filled, by = c("trading_date" = "date"))

```

```{r}
missing_values <- sapply(combined_speeches1, function(x) sum(is.na(x)))
print(missing_values)

```

```{r}
combined_speeches1$date<-as.Date(combined_speeches1$date, format = "%Y-%m-%d")
range(combined_speeches1$trading_date)

range(fedfunds_data$date)

range(ppi_data$date)

range(cpi_data$date)

range(balance_sheet_data$date)

```
```{r}
str(combined_speeches1$trading_date)
sum(is.na(combined_speeches1$trading_date))

missing_date_rows <- combined_speeches1 %>% filter(is.na(trading_date))

print(missing_date_rows)
combined_speeches1 <- combined_speeches1 %>% filter(!is.na(trading_date))

```
```{r}
date_sequence <- data.frame(date = seq(min(combined_speeches1$trading_date), max(combined_speeches1$trading_date), by = "day"))
cpi_data_daily <- date_sequence %>%
  left_join(cpi_data, by = "date") %>%
  arrange(date) %>%
  tidyr::fill(CPI, inflation_rate, .direction = "down")
ppi_data_daily <- date_sequence %>%
  left_join(ppi_data, by = "date") %>%
  arrange(date) %>%
  tidyr::fill(PPI, ppi_inflation_rate, .direction = "down")
fedfunds_data_daily <- date_sequence %>%
  left_join(fedfunds_data, by = "date") %>%
  arrange(date) %>%
  tidyr::fill(fed_funds_rate, .direction = "down")
balance_sheet_data_daily <- date_sequence %>%
  left_join(balance_sheet_data, by = "date") %>%
  arrange(date) %>%
  tidyr::fill(total_assets, .direction = "down")

```


```{r}
combined_speeches1 <- combined_speeches1 %>%
  left_join(cpi_data_daily %>% select(date, inflation_rate), by = c("trading_date" = "date"))

combined_speeches1 <- combined_speeches1 %>%
  left_join(ppi_data_daily %>% select(date, ppi_inflation_rate), by = c("trading_date" = "date"))

combined_speeches1 <- combined_speeches1 %>%
  left_join(fedfunds_data_daily %>% select(date, fed_funds_rate), by = c("trading_date" = "date"))

combined_speeches1 <- combined_speeches1 %>%
  left_join(balance_sheet_data_daily %>% select(date, total_assets), by = c("trading_date" = "date"))

```


```{r}
combined_speeches1 <- combined_speeches1 %>% select(-ends_with(".y"))
combined_speeches1 <- combined_speeches1 %>% select(-ends_with(".x"))
```

ANALYSIS:

```{r}
library(dplyr)
combined_speeches2<-combined_speeches1
combined_speeches2 <- combined_speeches2 %>%
  mutate(
    sentiment_label = case_when(
      label == "LABEL_0" ~ "Dovish",
      label == "LABEL_1" ~ "Hawkish",
      label == "LABEL_2" ~ "Neutral",
      TRUE ~ NA_character_
    ),
    sentiment_score = case_when(
      label == "LABEL_0" ~ -1,
      label == "LABEL_1" ~ 1,
      label == "LABEL_2" ~ 0,
      TRUE ~ NA_real_
    )
  )

```


```{r}
combined_speeches2 <- combined_speeches2 %>%
  group_by(date) %>%
  mutate(
    total_sentences = n(),
    hawkish_sentences = sum(sentiment_label == "Hawkish", na.rm = TRUE),
    dovish_sentences = sum(sentiment_label == "Dovish", na.rm = TRUE),
    neutral_sentences = sum(sentiment_label == "Neutral", na.rm = TRUE),
    hawkish_proportion = hawkish_sentences / total_sentences,
    dovish_proportion = dovish_sentences / total_sentences,
    neutral_proportion = neutral_sentences / total_sentences,
    avg_sentiment_score = mean(sentiment_score, na.rm = TRUE),
    dominant_sentiment = case_when(
      hawkish_sentences > dovish_sentences & hawkish_sentences > neutral_sentences ~ "Hawkish",
      dovish_sentences > hawkish_sentences & dovish_sentences > neutral_sentences ~ "Dovish",
      TRUE ~ "Neutral"
    )
  ) %>%
  ungroup()

```

```{r}
document_sentiment <- combined_speeches2 %>%
  select(date, type, total_sentences, hawkish_proportion, dovish_proportion,
         neutral_proportion, avg_sentiment_score, dominant_sentiment) %>%
  distinct()
```

```{r}
library(ggplot2)

sentiment_props <- document_sentiment %>%
  summarize(
    hawkish = mean(hawkish_proportion, na.rm = TRUE),
    dovish = mean(dovish_proportion, na.rm = TRUE),
    neutral = mean(neutral_proportion, na.rm = TRUE)
  )

sentiment_props_long <- sentiment_props %>%
  pivot_longer(cols = everything(), names_to = "sentiment", values_to = "proportion")

ggplot(sentiment_props_long, aes(x = sentiment, y = proportion, fill = sentiment)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Sentiment Proportions", x = "Sentiment", y = "Proportion") +
  theme_minimal()
```

```{r}
ggplot(document_sentiment, aes(x = date, y = avg_sentiment_score)) +
  geom_line() +
  labs(title = "Average Sentiment Score Over Time", x = "Date", y = "Average Sentiment Score") +
  theme_minimal()

```


```{r}
analysis_data <- document_sentiment %>%
  left_join(combined_speeches2 %>% select(date, sp500_return), by = "date")

ggplot(analysis_data, aes(x = avg_sentiment_score, y = sp500_return)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "S&P 500 Return vs. Average Sentiment Score", x = "Average Sentiment Score", y = "S&P 500 Return") +
  theme_minimal()

```

```{r}
comb=na.omit(comb)
analysis_data <- document_sentiment %>%
  left_join(comb %>% select(date, inflation_rate, ppi_inflation_rate, fed_funds_rate, sp500_return, VIX_close, DGS2, DGS10, yield_curve_slope, volume), by = "date")

```


```{r}
duplicates <- analysis_data %>%
  group_by(date, type) %>%
  filter(n() > 1) %>%
  arrange(date, type)
analysis_data <- analysis_data %>%
  arrange(date, type) %>%
  distinct(date, type, .keep_all = TRUE)
```
FORREAL ANALYSIS

PCA
```{r}
pca_data <- analysis_data %>%
  select(
    sp500_return, VIX_close, DGS2, DGS10, yield_curve_slope,
    fed_funds_rate, inflation_rate, ppi_inflation_rate,
    avg_sentiment_score, hawkish_proportion, dovish_proportion, neutral_proportion
  ) %>%
  na.omit()

```

```{r}
pca_result <- prcomp(pca_data, center = TRUE, scale. = TRUE)
summary(pca_result)

```
```{r}
plot(pca_result, type = "l", main = "Scree Plot")
variance_explained <- pca_result$sdev^2 / sum(pca_result$sdev^2)
cumulative_variance <- cumsum(variance_explained)
plot(cumulative_variance, type = "b", xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     main = "Cumulative Variance Explained by PCA")
```

```{r}
pca_loadings <- pca_result$rotation
print(pca_loadings)

```
```{r}
for (i in 1:4) {
  barplot(pca_result$rotation[, i], main = paste("PC", i), las = 2)
}
colnames(data)
pca_loadings <- pca_result$rotation
print(pca_loadings[,1:3])
```

```{r}
biplot(pca_result, scale = 0)

```

MDS

```{r}
pca_data_scaled <- scale(pca_data)

mds_data<-pca_data_scaled
distance_matrix <- dist(mds_data)
```

```{r}
analysis_data<-na.omit(analysis_data)
mds_result <- cmdscale(distance_matrix, k = 2, eig = TRUE)

mds_coordinates <- data.frame(
  Dim1 = mds_result$points[, 1],
  Dim2 = mds_result$points[, 2]
)

library(ggplot2)

ggplot(mds_coordinates, aes(x = Dim1, y = Dim2)) +
  geom_point() +
  labs(title = "MDS Plot", x = "Dimension 1", y = "Dimension 2") +
  theme_minimal()
mds_coordinates <- data.frame(
  Dim1 = mds_result$points[, 1],
  Dim2 = mds_result$points[, 2],
  dominant_sentiment = analysis_data$dominant_sentiment
)

ggplot(mds_coordinates, aes(x = Dim1, y = Dim2, color = dominant_sentiment)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(
    title = "MDS Plot Colored by Dominant Sentiment",
    x = "Dimension 1",
    y = "Dimension 2",
    color = "Dominant Sentiment"
  ) +
  theme_minimal()

mds_coordinates <- data.frame(
  Dim1 = mds_result$points[, 1],
  Dim2 = mds_result$points[, 2],
  fed_funds_rate = analysis_data$fed_funds_rate
)

ggplot(mds_coordinates, aes(x = Dim1, y = Dim2, color = fed_funds_rate)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(
    title = "MDS Plot Colored by FFR",
    x = "Dimension 1",
    y = "Dimension 2",
    color = "fed_funds_rate"
  ) +
  theme_minimal()

# Extract MDS coordinates
mds_coordinates <- data.frame(
  Dim1 = mds_result$points[, 1],
  Dim2 = mds_result$points[, 2],
  inflation_rate = analysis_data$inflation_rate
)

ggplot(mds_coordinates, aes(x = Dim1, y = Dim2, color = inflation_rate)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(
    title = "MDS Plot Colored by Inflation Rate",
    x = "Dimension 1",
    y = "Dimension 2",
    color = "inflation_rate"
  ) +
  theme_minimal()
```
```{r}

library(ape)

mst_edges <- mst(distance_matrix)
coords <- mds_result$points
edge_indices <- which(mst_edges != 0, arr.ind = TRUE)
edges_df <- data.frame(
  x1 = coords[edge_indices[, 1], 1],
  y1 = coords[edge_indices[, 1], 2],
  x2 = coords[edge_indices[, 2], 1],
  y2 = coords[edge_indices[, 2], 2]
)
ggplot(mds_coordinates, aes(x = Dim1, y = Dim2)) +
  geom_point(size = 3, alpha = 0.8) +
  # Add MST edges
  geom_segment(
    data = edges_df,
    aes(x = x1, y = y1, xend = x2, yend = y2),
    color = "gray50",
    size = 0.5
  ) +
  labs(
    title = "MDS Plot with Minimum Spanning Tree",
    x = "Dimension 1",
    y = "Dimension 2",
  ) +
  theme_minimal()


```




```{r}
pc_scores <- as.data.frame(pca_result$x[, 1:4])

regression_data <- cbind(pc_scores, sp500_return = pca_data$sp500_return)

lm_pc <- lm(sp500_return ~ ., data = regression_data)
summary(lm_pc)
```

```{r}
pc_scores <- as.data.frame(pca_result$x[, 1:3])

response_var <- analysis_data_unique$sp500_return[rownames(pc_scores)]
pcr_data <- cbind(pc_scores, sp500_return = response_var)



pcr_model <- lm(sp500_return ~ ., data = pcr_data)
summary(pcr_model)

```


TRADING STRAT

```{r}
analysis_data_unique <- analysis_data%>%
  mutate(
    position = case_when(
      dominant_sentiment %in% c("Dovish","Neutral" ~ 1,
      dominant_sentiment == "Hawkish" ~ -1,
      TRUE ~ 0  
      
    )
  )

analysis_data_unique <- analysis_data_unique %>%
  mutate(
    position_lag = lag(position, 1)
  )

analysis_data_unique$position_lag[is.na(analysis_data_unique$position_lag)] <- 0


```

```{r}
analysis_data_unique <- analysis_data_unique %>%
  mutate(
    strategy_return = position_lag * sp500_return
  )

```


```{r}
analysis_data_unique <- analysis_data_unique %>%
  mutate(
    cumulative_strategy_return = cumprod(1 + strategy_return) * 1000
  )

analysis_data_unique <- analysis_data_unique %>%
  mutate(
    cumulative_buy_hold = cumprod(1 + sp500_return) * 1000
  )

```

```{r}
library(tidyverse)
plot_data <- analysis_data_unique %>%
  select(date, cumulative_strategy_return, cumulative_buy_hold) %>%
  gather(key = "strategy", value = "cumulative_return", -date)

plot_data$strategy <- factor(plot_data$strategy,
                             levels = c("cumulative_strategy_return", "cumulative_buy_hold"),
                             labels = c("Sentiment Strategy", "Buy and Hold"))
ggplot(plot_data, aes(x = date, y = cumulative_return, color = strategy)) +
  geom_line(size = 1) +
  labs(
    title = "Cumulative Wealth Over Time",
    x = "Date",
    y = "Cumulative Wealth ($)",
    color = "Strategy"
  ) +
  theme_minimal() +
  scale_y_continuous(labels = scales::dollar_format(prefix = "$")) +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom"
  )

```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(scales)

analysis_data_unique$date <- as.Date(analysis_data$date)

analysis_data_unique <- analysis_data_unique %>%
  arrange(date) %>%
  mutate(
    position = case_when(
      dominant_sentiment %in% c("Dovish", "Neutral") ~ 1,
      dominant_sentiment == "Hawkish" ~ -1,
      TRUE ~ 0
    ),
    position_lag = lag(position, 1)
  )

analysis_data_unique$position_lag[is.na(analysis_data_unique$position_lag)] <- 0

analysis_data_unique <- analysis_data_unique %>%
  mutate(
    strategy_return = position_lag * sp500_return
  )

analysis_data_unique <- analysis_data_unique %>%
  mutate(
    cumulative_strategy_return = cumprod(1 + strategy_return) * 1000,
    cumulative_buy_hold = cumprod(1 + sp500_return) * 1000
  )

plot_data <- analysis_data_unique %>%
  select(date, cumulative_strategy_return, cumulative_buy_hold) %>%
  tidyr::gather(key = "strategy", value = "cumulative_return", -date)

plot_data$strategy <- factor(plot_data$strategy,
                             levels = c("cumulative_strategy_return", "cumulative_buy_hold"),
                             labels = c("Sentiment Strategy", "Buy and Hold"))

ggplot(plot_data, aes(x = date, y = cumulative_return, color = strategy)) +
  geom_line(size = 1) +
  labs(
    title = "Cumulative Wealth Over Time (Updated Strategy)",
    x = "Date",
    y = "Cumulative Wealth ($)",
    color = "Strategy"
  ) +
  theme_minimal() +
  scale_y_continuous(labels = dollar_format(prefix = "$")) +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom"
  )

```


```{r}
summary(data)

summary(data$sp500_return)

```
```{r}
plot(data$sp500_return ~ data$VIX_close, main = "S&P 500 Returns vs VIX", xlab = "VIX Close", ylab = "S&P 500 Return", col = "darkgreen")

correlation_matrix <- cor(data[, sapply(data, is.numeric)], use = "complete.obs")
print(correlation_matrix)

library(corrplot)
corrplot(correlation_matrix, method = "color", type = "lower", tl.col = "black", tl.cex = 0.8)

```

```{r}
ggplot(data, aes(x = dominant_sentiment, y = sp500_return)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "S&P 500 Returns by Sentiment Label", x = "Sentiment Label", y = "S&P 500 Return")


```

```{r}
library(GGally)
ggpairs(data[, c("sp500_return", "VIX_close", "DGS2", "DGS10", "fed_funds_rate", "ppi_inflation_rate","inflation_rate","volume")])

```

```{r}
library(ggcorrplot)
ggcorrplot(correlation_matrix, method = "circle", hc.order = TRUE, type = "lower", lab = TRUE)

```

```{r}
ggplot(data, aes(x = date, y = sp500_return)) +
  geom_line(color = "blue") +
  labs(title = "S&P 500 Returns Over Time", x = "Date", y = "S&P 500 Return")

```

```{r}
ggplot(data, aes(x = date, fill = dominant_sentiment)) +
  geom_bar() +
  labs(title = "Sentiment Over Time", x = "Date", y = "Count")

ggplot(data, aes(x = date, y = avg_sentiment_score)) +
  geom_line(color = "blue") +
  labs(title = "Average Sentiment Score Over Time", x = "Date", y = "Sentiment Score")

```



